### ISSUE TITLE
Script only works if I start it while loaded into the game

### ISSUE THREAD

**Issue by Nanorithm** [BuddyNotFound/bbv-realdmg#1]
Hey I've been messing around with this script and it seems like it only works when I start it after I'm already loaded into the game. If I start it with my server and laod in, vehicle damage doesn't work as intended. If I restart the script while I'm loaded in, everything works fine. If I log out and log back in, same issue as before where it's not working as intended.

**Comment by BuddyNotFound** [comment]
try to update and see if the issue persists.

**Comment by Nanorithm** [comment]
That fixed my issue, thanks for the quick response!
